sudo: false
language: android
script: "./gradlew build"
script:
  - ./gradlew build
  - ls
  - ls app/build/outputs/apk
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key:
    secure: # do command: `travis encrypt --add deploy.secret_access_key`to populate this field or generate the encrypted value
  bucket: "jisort"
  skip_cleanup: true
  local-dir: app/build/outputs/apk # will upload everything in this dir into the root of your s3 bucket
