sudo: false
language: android
script: "./gradlew build"
script:
  - ./gradlew build
  - ls
  - ls app/build/outputs/apk
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
notifications:
  email: false