sudo: false
language: android
jdk: oraclejdk8
script: "./gradlew build"
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
notifications:
  email: false